# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\formACT.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.ApplicationModal)
        Form.setEnabled(True)
        Form.resize(324, 205)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMaximumSize(QtCore.QSize(330, 327))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("#lbDir {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 1px solid;\n"
"border-color: grey;\n"
"color: grey;\n"
"}\n"
"#dp_update{\n"
"    margin: 10px 20px;\n"
"}")
        self.gridLayout_4 = QtWidgets.QGridLayout(Form)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSpacing(1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 100))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.lineAVK = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineAVK.setMinimumSize(QtCore.QSize(0, 26))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Book")
        font.setPointSize(11)
        self.lineAVK.setFont(font)
        self.lineAVK.setObjectName("lineAVK")
        self.gridLayout.addWidget(self.lineAVK, 0, 0, 1, 2)
        self.btnAVK = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.btnAVK.setFont(font)
        self.btnAVK.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btnAVK.setObjectName("btnAVK")
        self.gridLayout.addWidget(self.btnAVK, 1, 0, 1, 2)
        self.gridLayout_3.addWidget(self.groupBox_2, 2, 0, 1, 1)
        self.groupBox_1 = QtWidgets.QGroupBox(Form)
        self.groupBox_1.setMinimumSize(QtCore.QSize(0, 60))
        self.groupBox_1.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.groupBox_1.setFont(font)
        self.groupBox_1.setObjectName("groupBox_1")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lbDir = QtWidgets.QLabel(self.groupBox_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbDir.setFont(font)
        self.lbDir.setStyleSheet("")
        self.lbDir.setObjectName("lbDir")
        self.gridLayout_5.addWidget(self.lbDir, 0, 0, 1, 1)
        self.btnDir = QtWidgets.QPushButton(self.groupBox_1)
        self.btnDir.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.btnDir.setFont(font)
        self.btnDir.setAutoDefault(True)
        self.btnDir.setObjectName("btnDir")
        self.gridLayout_5.addWidget(self.btnDir, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_1, 0, 0, 1, 1)
        self.db_update = QtWidgets.QPushButton(Form)
        self.db_update.setObjectName("db_update")
        self.gridLayout_3.addWidget(self.db_update, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.lbDir.setBuddy(self.btnDir)

        self.retranslateUi(Form)
        self.btnAVK.clicked.connect(self.lineAVK.selectAll)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.btnDir, self.lineAVK)
        Form.setTabOrder(self.lineAVK, self.btnAVK)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "AFDsoft v1.3"))
        self.groupBox_2.setTitle(_translate("Form", "Акты ВК"))
        self.lineAVK.setToolTip(_translate("Form", "<html><head/><body><p>1-9<br/>ввести первую и последнию сторку Входного контроля</p></body></html>"))
        self.btnAVK.setText(_translate("Form", "Сохранить Word"))
        self.groupBox_1.setTitle(_translate("Form", "Папка для сохранения документов"))
        self.lbDir.setText(_translate("Form", "path"))
        self.btnDir.setText(_translate("Form", "Выбрать"))
        self.db_update.setText(_translate("Form", "Обновить базу"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
